import json
import glob
import os

CAT_TIPO_DESTINO = {"Agencia": 1, "Punto Fijo": 2}
CAT_DIAS_SEMANA = {"Lunes": 1, "Martes": 2, "Miércoles": 3, "Jueves": 4, "Viernes": 5, "Sábado": 6, "Domingo": 7, "Diario": 8}
CAT_REGLAS_CORTE = {"Mismo día": 1, "Día anterior": 2, "Día específico": 3}

def get_dia_id(nombre_dia):
    nombre_dia_cap = nombre_dia.capitalize()
    return CAT_DIAS_SEMANA.get(nombre_dia_cap, -1)

def get_tipo_id(tipo):
    # Puede venir 'Agencia', 'AGENCIA', 'Punto Fijo', etc.
    for k, v in CAT_TIPO_DESTINO.items():
        if k.lower() == tipo.lower():
            return v
    return 1 # Fallback a Agencia

def escape_sql(val):
    if val is None:
        return ""
    return str(val).replace("'", "''")

def main():
    base_dir = r"A:\SiVoyApp\data\normalized"
    json_files = glob.glob(os.path.join(base_dir, "norm_raw_*.json"))
    
    all_destinos = []
    for jf in json_files:
        with open(jf, 'r', encoding='utf-8') as f:
            data = json.load(f)
            all_destinos.extend(data)
            
    sql_file = r"A:\SiVoyApp\database\inserts_logistica_v3.sql"
    
    with open(sql_file, 'w', encoding='utf-8') as f:
        # 1. DDL
        f.write("-- ==========================================\n")
        f.write("-- DDL: CREACIÓN DE TABLAS NORMALIZADAS (V3)\n")
        f.write("-- ==========================================\n\n")
        
        f.write("CREATE TABLE CAT_TIPO_DESTINO (\n")
        f.write("    id_tipo_destino NUMBER PRIMARY KEY,\n")
        f.write("    descripcion VARCHAR2(50) NOT NULL UNIQUE\n")
        f.write(");\n\n")

        f.write("CREATE TABLE CAT_DIAS_SEMANA (\n")
        f.write("    id_dia NUMBER PRIMARY KEY,\n")
        f.write("    nombre_dia VARCHAR2(20) NOT NULL UNIQUE\n")
        f.write(");\n\n")

        f.write("CREATE TABLE CAT_REGLAS_CORTE (\n")
        f.write("    id_regla_corte NUMBER PRIMARY KEY,\n")
        f.write("    descripcion VARCHAR2(50) NOT NULL UNIQUE\n")
        f.write(");\n\n")

        f.write("CREATE TABLE DESTINOS (\n")
        f.write("    id_destino VARCHAR2(50) PRIMARY KEY,\n")
        f.write("    nombre_destino VARCHAR2(100) NOT NULL UNIQUE,\n")
        f.write("    id_tipo_destino NUMBER NOT NULL,\n")
        f.write("    departamento VARCHAR2(100),\n")
        f.write("    municipio VARCHAR2(100),\n")
        f.write("    direccion_referencia VARCHAR2(255),\n")
        f.write("    CONSTRAINT fk_destinos_tipo FOREIGN KEY (id_tipo_destino) REFERENCES CAT_TIPO_DESTINO(id_tipo_destino)\n")
        f.write(");\n\n")

        f.write("CREATE TABLE HORARIOS_OPERATIVOS (\n")
        f.write("    id_horario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    id_destino VARCHAR2(50) NOT NULL,\n")
        f.write("    id_dia NUMBER NOT NULL,\n")
        f.write("    hora_apertura VARCHAR2(5) NOT NULL,\n")
        f.write("    hora_cierre VARCHAR2(5) NOT NULL,\n")
        f.write("    CONSTRAINT fk_horarios_destino FOREIGN KEY (id_destino) REFERENCES DESTINOS(id_destino) ON DELETE CASCADE,\n")
        f.write("    CONSTRAINT fk_horarios_dia FOREIGN KEY (id_dia) REFERENCES CAT_DIAS_SEMANA(id_dia)\n")
        f.write(");\n\n")

        f.write("CREATE TABLE REGLAS_ENTREGA (\n")
        f.write("    id_regla NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n")
        f.write("    id_destino VARCHAR2(50) NOT NULL,\n")
        f.write("    id_dia_entrega NUMBER NOT NULL,\n")
        f.write("    id_regla_corte NUMBER NOT NULL,\n")
        f.write("    id_dia_corte_especifico NUMBER,\n")
        f.write("    CONSTRAINT fk_reglas_destino FOREIGN KEY (id_destino) REFERENCES DESTINOS(id_destino) ON DELETE CASCADE,\n")
        f.write("    CONSTRAINT fk_reglas_dia_entrega FOREIGN KEY (id_dia_entrega) REFERENCES CAT_DIAS_SEMANA(id_dia),\n")
        f.write("    CONSTRAINT fk_reglas_tipo_corte FOREIGN KEY (id_regla_corte) REFERENCES CAT_REGLAS_CORTE(id_regla_corte),\n")
        f.write("    CONSTRAINT fk_reglas_dia_corte_esp FOREIGN KEY (id_dia_corte_especifico) REFERENCES CAT_DIAS_SEMANA(id_dia)\n")
        f.write(");\n\n")
        
        # 2. DML CATÁLOGOS
        f.write("-- ==========================================\n")
        f.write("-- DML: POBLADO DE CATÁLOGOS\n")
        f.write("-- ==========================================\n\n")
        f.write("INSERT ALL\n")
        for k, v in CAT_TIPO_DESTINO.items():
            f.write(f"  INTO CAT_TIPO_DESTINO (id_tipo_destino, descripcion) VALUES ({v}, '{k}')\n")
        f.write("SELECT * FROM dual;\n\n")

        f.write("INSERT ALL\n")
        for k, v in CAT_DIAS_SEMANA.items():
            f.write(f"  INTO CAT_DIAS_SEMANA (id_dia, nombre_dia) VALUES ({v}, '{k}')\n")
        f.write("SELECT * FROM dual;\n\n")

        f.write("INSERT ALL\n")
        for k, v in CAT_REGLAS_CORTE.items():
            f.write(f"  INTO CAT_REGLAS_CORTE (id_regla_corte, descripcion) VALUES ({v}, '{k}')\n")
        f.write("SELECT * FROM dual;\n\n")

        # 3. DML DESTINOS
        f.write("-- ==========================================\n")
        f.write("-- DML: POBLADO DE DATOS (DESTINOS)\n")
        f.write("-- ==========================================\n\n")
        f.write("INSERT ALL\n")
        
        for d in all_destinos:
            if not isinstance(d, dict): continue
            
            id_dest = escape_sql(d.get('id_destino'))
            nombre = escape_sql(d.get('nombre_destino'))
            id_tipo = get_tipo_id(d.get('tipo', 'Agencia'))
            ubi = d.get('ubicacion', {})
            dep = escape_sql(ubi.get('departamento'))
            mun = escape_sql(ubi.get('municipio'))
            dir_ref = escape_sql(ubi.get('direccion_referencia'))
            
            f.write(f"  INTO DESTINOS (id_destino, nombre_destino, id_tipo_destino, departamento, municipio, direccion_referencia) ")
            f.write(f"VALUES ('{id_dest}', '{nombre}', {id_tipo}, '{dep}', '{mun}', '{dir_ref}')\n")
        f.write("SELECT * FROM dual;\n\n")
        
        # 4. DML HORARIOS
        f.write("-- ==========================================\n")
        f.write("-- DML: POBLADO DE HORARIOS OPERATIVOS\n")
        f.write("-- ==========================================\n\n")
        f.write("INSERT ALL\n")
        horario_id = 1
        for d in all_destinos:
            if not isinstance(d, dict): continue
            id_dest = escape_sql(d.get('id_destino'))
            for h in d.get('horarios_operativos', []):
                id_dia = get_dia_id(h['dia_semana'])
                aper = escape_sql(h['hora_apertura'])
                cier = escape_sql(h['hora_cierre'])
                f.write(f"  INTO HORARIOS_OPERATIVOS (id_horario, id_destino, id_dia, hora_apertura, hora_cierre) ")
                f.write(f"VALUES ({horario_id}, '{id_dest}', {id_dia}, '{aper}', '{cier}')\n")
                horario_id += 1
        f.write("SELECT * FROM dual;\n\n")
        
        # 5. DML REGLAS
        f.write("-- ==========================================\n")
        f.write("-- DML: POBLADO DE REGLAS DE ENTREGA\n")
        f.write("-- ==========================================\n\n")
        f.write("INSERT ALL\n")
        regla_id = 1
        for d in all_destinos:
            if not isinstance(d, dict): continue
            id_dest = escape_sql(d.get('id_destino'))
            for r in d.get('reglas_entrega', []):
                id_dia_ent = get_dia_id(r['dia_entrega'])
                
                corte_raw = r['dia_corte_maximo'].capitalize()
                id_regla_corte = 2 # Default: Día anterior
                id_dia_corte_esp = "NULL"
                
                if corte_raw == "Mismo día":
                    id_regla_corte = 1
                elif corte_raw == "Día anterior" or corte_raw == "Dia anterior":
                    id_regla_corte = 2
                else:
                    # Es un día específico
                    id_regla_corte = 3
                    id_dia_corte_esp = get_dia_id(corte_raw)
                    if id_dia_corte_esp == -1:
                        # Fallback
                        id_regla_corte = 2
                        id_dia_corte_esp = "NULL"
                
                f.write(f"  INTO REGLAS_ENTREGA (id_regla, id_destino, id_dia_entrega, id_regla_corte, id_dia_corte_especifico) ")
                f.write(f"VALUES ({regla_id}, '{id_dest}', {id_dia_ent}, {id_regla_corte}, {id_dia_corte_esp})\n")
                regla_id += 1
        f.write("SELECT * FROM dual;\n\n")

    print(f"Éxito: Generado {sql_file}")

if __name__ == '__main__':
    main()
