INSERT ALL
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (1, 'Acajutla', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (2, 'Agua Caliente', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (3, 'Aguilares', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (4, 'Ahuachapán', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (5, 'Alegría', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (6, 'Altavista', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (7, 'Anamorós', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (8, 'Antiguo Cuscatlán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (9, 'Apaneca', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (10, 'Apastepeque', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (11, 'Apopa', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (12, 'Arambala', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (13, 'Armenia', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (14, 'Ataco', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (15, 'Ateos', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (16, 'Atiquizaya', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (17, 'Berlín', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (18, 'Bolívar', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (19, 'Cacaopera', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (20, 'Candelaria de la Frontera', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (21, 'Cara Sucia', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (22, 'Chalatenango', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (23, 'Chapeltique', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (24, 'Chilanga', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (25, 'Chinameca', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (26, 'Chirilagua', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (27, 'Ciudad Arce', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (28, 'Ciudad Barrios', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (29, 'Ciudad Delgado', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (30, 'Ciudad El Triunfo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (31, 'Ciudad Marsella', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (32, 'Ciudad Real', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (33, 'Ciudad Versalles', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (34, 'Coatepeque', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (35, 'Cojutepeque', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (36, 'Comacarán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (37, 'Concepción Batres', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (38, 'Concepción de Oriente', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (39, 'Conchagua', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (40, 'Corinto', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (41, 'Delicias de Concepción', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (42, 'Dolores', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (43, 'El Amatillo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (44, 'El Carmen', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (45, 'El Congo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (46, 'El Divisadero', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (47, 'El Paraíso', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (48, 'El Refugio', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (49, 'El Rosario, La Paz', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (50, 'El Sauce', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (51, 'El Tránsito', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (52, 'Ereguayquín', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (53, 'Estanzuelas', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (54, 'Gualococti', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (55, 'Guatajiagua', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (56, 'Guaymango', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (57, 'Guazapa', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (58, 'Ilopango', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (59, 'Ilobasco', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (60, 'Intipucá', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (61, 'Izalco', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (62, 'Jiquilisco', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (63, 'Jocoaitique', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (64, 'Jocoro', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (65, 'Juayúa', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (66, 'Jucuapa', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (67, 'Jucuarán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (68, 'Jujutla', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (69, 'La Gran Vía', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (70, 'La Palma', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (71, 'La Unión', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (72, 'Lislique', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (73, 'Lolotique', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (74, 'Lolotiquillo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (75, 'Los Naranjos', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (76, 'Lourdes', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (77, 'Mercedes Umaña', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (78, 'Metapán', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (79, 'Metalío', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (80, 'Moncagua', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (81, 'Nahuizalco', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (82, 'Nejapa', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (83, 'Nueva Concepción', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (84, 'Nueva Esparta', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (85, 'Nueva Granada', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (86, 'Nueva Guadalupe', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (87, 'Nuevo Edén de San Juan', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (88, 'Olocuilta', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (89, 'Opico Centro', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (90, 'Osicala', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (91, 'Ozatlán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (92, 'Paraje Galán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (93, 'Pasaquina', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (94, 'Paseo Venecia', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (95, 'Perquín', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (96, 'Planes de Renderos', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (97, 'Playa El Cuco', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (98, 'Playa El Espino', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (99, 'Plaza Don Yon', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (100, 'Plaza Merliot', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (101, 'Plaza Mundo Soyapango', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (102, 'Plaza San Jacinto', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (103, 'Plaza Santo Tomás', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (104, 'Polorós', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (105, 'Puerto de la Libertad', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (106, 'Puerto El Triunfo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (107, 'Puerto Parada', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (108, 'Quelepa', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (109, 'Quezaltepeque', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (110, 'Salcoatitán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (111, 'Salvador del Mundo', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (112, 'San Alejo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (113, 'San Antonio Pajonal', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (114, 'San Bartolo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (115, 'San Bartolomé Perulapía', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (116, 'San Buenaventura', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (117, 'San Carlos', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (118, 'San Esteban Catarina', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (119, 'San Francisco Gotera', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (120, 'San Gerardo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (121, 'San Ignacio', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (122, 'San Ildefonso', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (123, 'San Isidro', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (124, 'San Juan Nonualco', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (125, 'San Juan Talpa', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (126, 'San Julián', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (127, 'San Luis de la Reina', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (128, 'San Luis Talpa', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (129, 'San Marcos Lempa', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (130, 'San Martín', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (131, 'San Matías', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (132, 'San Miguel', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (133, 'San Miguel Hato Nuevo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (134, 'San Pedro Perulapán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (135, 'San Rafael Cedros', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (136, 'San Rafael Obrajuelos', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (137, 'San Rafael Oriente', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (138, 'San Salvador (Metrogalerías)', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (139, 'San Salvador Centro', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (140, 'San Sebastián', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (141, 'San Simón', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (142, 'San Vicente', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (143, 'Santa Ana Centro', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (144, 'Santa Ana Plaza 33', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (145, 'Santa Elena', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (146, 'Santa María', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (147, 'Santa Rosa de Lima', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (148, 'Santa Tecla', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (149, 'Santiago de la Frontera', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (150, 'Santiago de María', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (151, 'Santiago Nonualco', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (152, 'Santiago Texacuangos', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (153, 'Santo Domingo', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (154, 'Senzembra', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (155, 'Sensuntepeque', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (156, 'Sesori', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (157, 'Sociedad', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (158, 'Sonzacate', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (159, 'Sonsonate', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (160, 'Soyapango', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (161, 'Soyapango (Unicentro)', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (162, 'Suchitoto', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (163, 'Tacachico', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (164, 'Tecapán', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (165, 'Tecoluca', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (166, 'Tejutepeque', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (167, 'Texistepeque', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (168, 'Tierra Blanca', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (169, 'Tonacatepeque', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (170, 'Turín', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (171, 'Uluazapa', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (172, 'Usulután', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (173, 'Yamabal', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (174, 'Yoloaiquín', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (175, 'Yucuaiquín', 'Punto Fijo')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (176, 'Zacatecoluca', 'Agencia')
INTO DESTINOS (id_destino, nombre_destino, tipo) VALUES (177, 'Zaragoza', 'Punto Fijo')
SELECT 1 FROM DUAL;

INSERT ALL
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (1, 1, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (2, 2, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (3, 2, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (4, 3, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (5, 3, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (6, 4, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (7, 5, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (8, 5, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (9, 6, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (10, 7, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (11, 7, 'Domingo', 'Viernes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (12, 8, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (13, 8, 'Sábado', 'Viernes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (14, 9, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (15, 9, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (16, 10, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (17, 10, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (18, 11, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (19, 12, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (20, 13, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (21, 14, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (22, 14, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (23, 15, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (24, 15, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (25, 16, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (26, 17, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (27, 18, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (28, 19, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (29, 19, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (30, 20, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (31, 21, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (32, 22, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (33, 23, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (34, 23, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (35, 24, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (36, 25, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (37, 25, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (38, 26, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (39, 26, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (40, 27, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (41, 28, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (42, 28, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (43, 29, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (44, 29, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (45, 30, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (46, 30, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (47, 31, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (48, 31, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (49, 32, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (50, 32, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (51, 33, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (52, 33, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (53, 34, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (54, 34, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (55, 35, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (56, 36, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (57, 37, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (58, 37, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (59, 38, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (60, 39, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (61, 39, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (62, 40, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (63, 40, 'Domingo', 'Viernes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (64, 41, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (65, 42, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (66, 42, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (67, 43, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (68, 43, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (69, 44, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (70, 44, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (71, 45, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (72, 45, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (73, 46, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (74, 46, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (75, 47, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (76, 47, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (77, 48, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (78, 48, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (79, 49, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (80, 49, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (81, 50, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (82, 51, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (83, 52, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (84, 53, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (85, 53, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (86, 54, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (87, 55, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (88, 56, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (89, 56, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (90, 57, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (91, 57, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (92, 58, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (93, 58, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (94, 59, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (95, 59, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (96, 60, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (97, 60, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (98, 61, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (99, 62, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (100, 63, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (101, 64, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (102, 64, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (103, 65, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (104, 65, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (105, 66, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (106, 66, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (107, 67, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (108, 68, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (109, 68, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (110, 69, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (111, 69, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (112, 70, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (113, 70, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (114, 71, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (115, 72, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (116, 72, 'Domingo', 'Viernes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (117, 73, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (118, 73, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (119, 74, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (120, 75, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (121, 75, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (122, 76, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (123, 77, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (124, 77, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (125, 78, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (126, 79, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (127, 80, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (128, 80, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (129, 81, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (130, 81, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (131, 82, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (132, 83, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (133, 84, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (134, 84, 'Domingo', 'Viernes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (135, 85, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (136, 86, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (137, 86, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (138, 87, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (139, 87, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (140, 88, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (141, 88, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (142, 89, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (143, 89, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (144, 90, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (145, 90, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (146, 91, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (147, 92, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (148, 92, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (149, 93, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (150, 93, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (151, 94, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (152, 94, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (153, 95, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (154, 96, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (155, 96, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (156, 97, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (157, 97, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (158, 98, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (159, 99, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (160, 99, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (161, 100, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (162, 100, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (163, 101, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (164, 101, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (165, 102, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (166, 102, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (167, 103, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (168, 103, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (169, 104, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (170, 104, 'Domingo', 'Viernes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (171, 105, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (172, 105, 'Sábado', 'Viernes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (173, 106, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (174, 106, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (175, 107, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (176, 108, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (177, 109, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (178, 110, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (179, 110, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (180, 111, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (181, 111, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (182, 112, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (183, 112, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (184, 113, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (185, 113, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (186, 114, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (187, 114, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (188, 115, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (189, 115, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (190, 116, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (191, 117, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (192, 118, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (193, 118, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (194, 119, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (195, 120, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (196, 120, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (197, 121, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (198, 121, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (199, 122, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (200, 122, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (201, 123, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (202, 123, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (203, 124, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (204, 124, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (205, 125, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (206, 125, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (207, 126, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (208, 126, 'Domingo', 'Sábado')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (209, 127, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (210, 127, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (211, 128, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (212, 128, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (213, 129, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (214, 129, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (215, 130, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (216, 131, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (217, 131, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (218, 132, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (219, 133, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (220, 134, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (221, 134, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (222, 135, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (223, 135, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (224, 136, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (225, 136, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (226, 137, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (227, 137, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (228, 138, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (229, 139, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (230, 140, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (231, 140, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (232, 141, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (233, 142, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (234, 143, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (235, 144, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (236, 145, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (237, 145, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (238, 146, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (239, 147, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (240, 148, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (241, 149, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (242, 149, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (243, 150, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (244, 151, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (245, 151, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (246, 152, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (247, 152, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (248, 153, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (249, 153, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (250, 154, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (251, 155, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (252, 155, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (253, 156, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (254, 156, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (255, 157, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (256, 157, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (257, 158, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (258, 159, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (259, 160, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (260, 161, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (261, 162, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (262, 162, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (263, 163, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (264, 163, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (265, 164, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (266, 165, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (267, 165, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (268, 166, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (269, 166, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (270, 167, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (271, 167, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (272, 168, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (273, 168, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (274, 169, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (275, 169, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (276, 170, 'Martes', 'Lunes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (277, 170, 'Viernes', 'Jueves')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (278, 171, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (279, 172, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (280, 173, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (281, 174, 'Jueves', 'Miércoles')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (282, 175, 'Lunes', 'Domingo')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (283, 176, 'Diario', 'Día anterior')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (284, 177, 'Miércoles', 'Martes')
INTO REGLAS_ENTREGA (id_regla, id_destino, dia_entrega, dia_corte) VALUES (285, 177, 'Sábado', 'Viernes')
SELECT 1 FROM DUAL;
